DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS bed;

CREATE TABLE bed
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL,
    specialty_id BIGINT NOT NULL,
    available BOOLEAN NOT NULL
);

CREATE TABLE reservation
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bed_id BIGINT NOT NULL,
    patient_latitude DOUBLE PRECISION NOT NULL,
    patient_longitude DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_reservation_bed
        FOREIGN KEY (bed_id)
            REFERENCES bed(id)
);