spring:
  application:
    name: recommendation-service

services:
  hospital:
    base-url: http://localhost:8085

  bed:
    base-url: http://localhost:8086

  routing:
    base-url: http://localhost:8087
server:
  port: 8088

logging:
  level:
    org.springframework.http.converter.json: TRACE