DROP TABLE IF EXISTS recommendation;

CREATE TABLE recommendation
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialty_id BIGINT NOT NULL,
    patient_latitude DOUBLE PRECISION NOT NULL,
    patient_longitude DOUBLE PRECISION NOT NULL,
    distance_km DOUBLE PRECISION,
    status VARCHAR(50),
    created_at TIMESTAMP
);